spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLDialect

    show-sql: true
  mail:
    port: 587
    host: smtp.gmail.com
    username: "gietuallinone@gmail.com"
    password: "imdu znnk gsuy mxid"

    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      mail :
        smtp :
          auth : true
          starttls :
            enable : true


